
# Pull the Node image from Docker Hub
FROM node:16-slim

RUN apt-get update && \
      apt-get -y install sudo

RUN sudo su

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 3080

RUN chmod +x node_modules/.bin/nodemon

# Run the React app
CMD ["npm", "start"]